version: 2
jobs:
  build:
    working_directory: /go/src/github.com/drn/nerd-ls
    docker:
      - image: circleci/golang:1.11.2
    steps:
      - checkout
      - run: go get ./...
      - run:
          name: Lint
          command: |
            go get -u golang.org/x/lint/golint
            golint -set_exit_status ./...
      - run:
          name: Test
          command: |
            go get -u github.com/smartystreets/goconvey
            go test ./... -v
      - run:
          name: Compact
          command: |
            nerd-ls
      - run:
          name: Compact, All
          command: |
            nerd-ls -a
      - run:
          name: Long
          command: |
            nerd-ls -l
      - run:
          name: Long, All
          command: |
            nerd-ls -la
