version: 2
jobs:
  build:
    working_directory: /go/src/github.com/drn/nerd-ls
    docker:
      - image: circleci/golang:1.11.2
    steps:
      - checkout
      - run: go get ./...
      - run:
          name: Lint
          command: |
            go get -u golang.org/x/lint/golint
            golint -set_exit_status ./...
      - run:
          name: Test
          command: |
            go get -u github.com/smartystreets/goconvey
            go test ./... -v
      - run:
          name: Compact
          command: |
            echo "\nnerd-ls"; nerd-ls
            echo "\nnerd-ls -a"; nerd-ls -a
            echo "\nnerd-ls -ai"; nerd-ls -ai
            echo "\nnerd-ls -ai /"; nerd-ls -ai /
      - run:
          name: Long
          command: |
            echo "\nnerd-ls -l"; nerd-ls -l
            echo "\nnerd-ls -al"; nerd-ls -al
            echo "\nnerd-ls -ail"; nerd-ls -ail
            echo "\nnerd-ls -ail /"; nerd-ls -ail /
